import type { LeadDetailsFormData } from "@/types/lead/lead-details.types";

export const leadDetailsDefaultFormValues: LeadDetailsFormData = {
  leadCode: "",
  fullName: "",
  gender: "",
  contactNumber: "",
  email: "",
  leadSource: "",
  leadStage: "",
  leadStatus: "",
  assignTo: "",
  interestedProducts: "",
  remarks: "",
  addressType: "",
  houseNo: "",
  streetLane: "",
  placeName: "",
  pincode: "",
  country: "",
  state: "",
  district: "",
  postOfficeId: "",
  city: "",
  landmark: "",
  digipin: "",
  latitude: "",
  longitude: "",
  addressProofType: "",
  documentFile: undefined,
  additionalReferences: {},
  nextFollowUpDate: "",
  preferredTime: "",
  leadProbability: null,
  highPriority: false,
  canvassedTypeIdentity: "",
  canvasserIdentity: "",
};
