import type { LoanSchemeFormData } from "@/types/loan-product-and schema Stepper/index";

export const loanSchemeDefaultFormValues: LoanSchemeFormData = {
  loanProductName: "",
  schemeCode: "",
  schemeName: "",
  schemeTypeName: "",
  effectiveFrom: "",
  effectiveTo: "",
  fromAmount: "",
  toAmount: "",
  minimumPeriod: "",
  minPeriodTypeName: "",
  periodTypeName: "",
  maximumPeriod: "",
  maxPeriodTypeName: "",
  interestTypeName: "",
  fixedInterestRate: "",
  penalInterest: "",
  penalInterestBaseName: "",
  rebateBaseName: "",
  rebatePercentage: "",
  gracePeriod: "",
  moratoriumInterestRate: "",
  remarks: "",
  penalInterestApplicable: false,
  reverseInterestApplicable: false,
  moratoriumInterestRequired: false,
  rebateApplicable: false,
  emiApplicable: false,
  takeoverScheme: false,
  coLendingScheme: false,
  active: true,
};

export const VALIDATION_RULES = {
  REQUIRED_FIELDS: {
    loanProductName: "Loan product is required",
    schemeCode: "Scheme code is required",
    schemeName: "Scheme name is required",
    schemeTypeName: "Scheme type is required",
    effectiveFrom: "Effective from date is required",
    fromAmount: "From amount is required",
    toAmount: "To amount is required",
    minPeriodTypeName: "Minimum period is required",
    maxPeriodTypeName: "Period type is required",
    interestTypeName: "Interest type flag is required",
    fixedInterestRate: "Fixed interest rate is required",
  },
  PATTERNS: {
    AMOUNT: {
      value: /^[0-9]+(\.[0-9]{1,2})?$/,
      message: "Enter valid amount",
    },
    PERCENTAGE: {
      value: /^[0-9]+(\.[0-9]{1,2})?$/,
      message: "Enter valid percentage",
    },
    INTEGER: {
      value: /^[0-9]+$/,
      message: "Enter valid number",
    },
    ALPHANUMERIC: {
      value: /^[a-zA-Z0-9\s]+$/,
      message: "Only letters, numbers and spaces allowed",
    },
  },
  LIMITS: {
    AMOUNT: {
      MIN: 1,
      MIN_MESSAGE: "Amount must be greater than 0",
    },
    PERCENTAGE: {
      MIN: 0,
      MAX: 100,
      MIN_MESSAGE: "Percentage cannot be negative",
      MAX_MESSAGE: "Percentage cannot exceed 100%",
    },
    INTEREST_RATE: {
      MIN: 0.01,
      MAX: 100,
      MIN_MESSAGE: "Interest rate must be greater than 0",
      MAX_MESSAGE: "Interest rate cannot exceed 100%",
    },
    PERIOD: {
      MIN: 1,
      MIN_MESSAGE: "Period must be greater than 0",
    },
    GRACE_PERIOD: {
      MIN: 0,
      MIN_MESSAGE: "Grace period cannot be negative",
    },
  },
};

export const FIELD_LABELS = {
  loanProduct: "Loan Product",
  schemeCode: "Scheme Code",
  schemeName: "Scheme Name",
  schemeType: "Scheme Type",
  effectiveFrom: "Effective From",
  effectiveTo: "Effective To",
  fromAmount: "From Amount",
  toAmount: "To Amount",
  minimumPeriod: "Minimum Period",
  periodType: "Period Type",
  maximumPeriod: "Maximum Period",
  maxPeriodTypeName: "Period Type",
  interestTypeFlag: "Interest Type Flag",
  fixedInterestRate: "Fixed Interest Rate",
  penalInterest: "Penal Interest",
  penalInterestOn: "Penal Interest On",
  rebateOn: "Rebate On",
  rebatePercentage: "Rebate %",
  gracePeriod: "Grace Period",
  moratoriumInterestRate: "Moratorium Interest Rate",
  remarks: "Remarks",
  penalInterestApplicable: "Penal Interest Applicable",
  reverseInterestApplicable: "Reverse Interest Applicable",
  moratoriumInterestRequired: "Moratorium Interest Variation Required",
  rebateApplicable: "Rebate",
  active: "Active",
};

export const PLACEHOLDERS = {
  loanProduct: "Select loan product",
  schemeCode: "Auto-generate new record",
  schemeName: "Enter scheme name",
  schemeType: "Select scheme type",
  effectiveFrom: "dd-mm-yyyy",
  effectiveTo: "dd-mm-yyyy",
  fromAmount: "Enter From Amount",
  toAmount: "Enter To Amount",
  minimumPeriod: "Enter period",
  periodType: "Select period type",
  maximumPeriod: "Enter period",
  maxPeriodTypeName: "Select period type",
  interestTypeFlag: "Select interest Type Flag",
  fixedInterestRate: "Enter Fixed Interest Rate",
  penalInterest: "Enter Penal Interest",
  penalInterestOn: "Select Penal interest on",
  rebateOn: "Select Rebate on",
  rebatePercentage: "Enter Rebate Percentage",
  gracePeriod: "Enter Grace Period",
  moratoriumInterestRate: "Enter Moratorium Interest Rate",
  remarks: "Enter remarks",
};
