export * from "./auth";
export * from "./menu/menu";
export * from "./customer/customer";
export * from "./customer/basic";
export * from "./customer/form60";
export * from "./customer/kyc";
export * from "./customer/nominee";
export * from "./customer/photo";
export * from "./customer/address";
export * from "./customer/contact";
export * from "./customer/additional";
export * from "./customer/bank";
export * from "./customer/all-details";
export * from "./customer/canvasser";
export * from "./master/master";
export * from "./lead/lead-assignment";
// export * from "./master/lead-master";
// export * from "./master/firm-master";
export * from "./Firm/firmDetails";
export * from "./Firm/BusinessDetails";
// export * from "./Firm/FirmProfile";
export * from "./Firm/firm-photo";
export * from "./files/dms-upload";
export * from "./loan-product-and-scheme/gl-mappings";
export * from "./loan-product-and-scheme/document-requirements";
export * from "./loan-product-and-scheme/business-rules";
