import type { TenantType } from "@/types/customer-management/tenant";

export const TENANT_DEFAULT_VALUES: TenantType = {
  tenantName: "",
  tenantCode: "",
  id: "",
  tenantAddress: {
    addressType: "",
    streetLaneName: "",
    placeName: "",
    pinCode: undefined,
    country: "",
    state: "",
    district: "",
    postOffice: "",
    city: "",
    landmark: "",
    siteFactoryPremise: "",
    nameOfTheOwner: "",
    relationshipWithTenant: "",
    landlineNumber: "",
    timeZone: "",
  },
  legalEntityName: "",
  tenantType: "",
  registrationNo: "",
  rbiRegistrationNumber: "",
  panNumber: "",
  gstNumber: "",
  cinNumber: "",
  contactNumber: "",
  website: "",
  businessEmail: "",
  chooseFile: null,
  attributes: [],
  isActive: true
};
