import { createApi } from "@reduxjs/toolkit/query/react";
import { axiosBaseQuery } from "./base-query";
import { ENV } from "@/config";

export const apiInstance = createApi({
  reducerPath: "api",
  baseQuery: axiosBaseQuery({
    baseUrl: ENV.VITE_BACKEND_BASE_URL,
  }),
  tagTypes: [
    "CustomerPhoto",
    "Customer",
    "Photo",
    "BasicInfo",
    "Nominee",
    "KycDocuments",
    "AddressOptions",
    "AddressProofTypes",
    "AddressDocuments",
    "CustomerAddresses",
    "CustomerContacts",
    "AddressProofType",
    "Form60",
    "Canvasser",
    "SitePremise",
    "AddressTypes",
    "EntityTypes",
    "PostOffices",
    "LocationData",
    "PincodeDetails",
    "FirmPincode",
    "FirmAddresses",
    "BankAccounts",
    "FirmPhotos",
    "BusinessInfo",
    "FirmDetails",
    "FirmBankAccounts",
    "Workflows",
    "Roles",
    "WorkflowStages",
    "UserLeaveStatus",
    "BranchDetails",
    "UserDetails",
    "ApprovalQueue",
    "Users",
    "Modules",
    "UserDelegations",
    "ApprovalFlows",
    "AmountOnOptions",
    "WorkflowAmountRules",
    "IndustryCategory",
    "DocumentType",
    "Occupation",
    "Purpose",
    "RiskCategory",
    "LeadSources",
    "Designation",
    "ReferralSource",
    "Bank",
    "Country",
    "FirmType",
    "SectoralPerformances",
    "FirmRole",
    "Staff",
    "SourceOfIncome",
    "BranchContact",
    "CustomerCategory",
    "LoanSchemePropertyValues",
    "InterestSlab",
    "LTVSlab",
    "GLMapping",
    "DocumentRequirement",
    "RecoveryPriority",
    "ChargeSlabs",
    "BusinessRule",
    "Staff",
    "UserRole",
    "RiskAssessmentType",
    "RoleManagement",
    ],
  endpoints: () => ({}),
});
